version: 2
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
